name: build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Go
        uses: actions/setup-go@v5
        env:
          GO111MODULE: "on"
        with:
          go-version: '1.21'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4

      - run: make style
      - run: make vet
      - run: make test
      - run: make build BRANCH=${{ github.head_ref || github.ref_name }}
      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
      - run: make integ
