name: Docker image

on: [push]
  # push:
  #   paths:
  #   - 'Dockerfile'
  #   - '.github/workflows/docker-image.yml'
  #   - '**/*.go'
  #   - 

jobs:

  image:
    runs-on: ubuntu-latest
    steps:

      - name: set some var
        id: docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          if [ ${{ env.DOCKER_USERNAME != '' && github.event_name != 'pull_request' }} == true ];then
            echo "push=true" >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
            echo platforms=linux/amd64 >> $GITHUB_OUTPUT
          fi
          
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: ${{ env.DOCKER_USERNAME != '' && github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@master

      - name: generate docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            zhangguanzhang/process-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
#            type=sha
# https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver

      

      - name: build docker image and, if not PR, push
        uses: docker/build-push-action@v5
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          file: ./Dockerfile
          context: .
          platforms: ${{ steps.docker.outputs.platforms }}
          push: ${{ steps.docker.outputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: ${{ github.triggering_actor != env.DOCKER_USERNAME || github.event_name == 'pull_request' }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zhangguanzhang/process-exporter
        if: github.ref == 'refs/heads/master'
